networks:
  phpinfo:
  
services:
  phpinfo:
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
    expose:
      - 8080
    image: paaragon/ibm-phpinfo:latest
    networks:
      - phpinfo
    ports:
      - 80:8080
version: "3.8"
